DROP TRIGGER INCREASE_COPIES;
DROP TRIGGER DECREASE_COPIES;


PROMPT DROP TABLES;


DROP TABLE BOOK CASCADE CONSTRAINT;
DROP TABLE STUDENT CASCADE CONSTRAINT;
DROP TABLE RESERVE CASCADE CONSTRAINT;
DROP TABLE BORROW_RECORD CASCADE CONSTRAINT;